name: Docker Build and Push
description: Builds and pushes Docker image to GHCR and optionally Docker Hub with versioning

inputs:
  service_name:
    description: 'Service name for image tagging (e.g., yarmcp-mcp)'
    required: true
  context_path:
    description: 'Build context path (e.g., ./mcp-server)'
    required: true
  dockerfile:
    description: 'Path to Dockerfile (optional, defaults to Dockerfile in context)'
    required: false
  ghcr_token:
    description: 'GHCR authentication token (usually GITHUB_TOKEN)'
    required: true
  dockerhub_username:
    description: 'Docker Hub username (optional, for pushing to Docker Hub in dev mode)'
    required: false
  dockerhub_token:
    description: 'Docker Hub token (optional, for pushing to Docker Hub in dev mode)'
    required: false
  build_args:
    description: 'Build arguments (optional)'
    required: false
  build_mode:
    description: 'Build mode: "dev" (build+push edge/dev tags to GHCR+DockerHub), "test" (build only), "release" (build+push version tag to GHCR only)'
    required: false
    default: 'dev'
  docker_tag:
    description: 'Docker-safe version tag for releases (e.g., 1.0.0) - required for build_mode=release'
    required: false
  full_version:
    description: 'Full version with commit hash (e.g., 1.0.0+abc1234) - used in OCI labels only'
    required: false
  run_tests:
    description: 'Run Python tests after build (default: true for test/release modes, false for dev mode)'
    required: false
    default: 'auto'

runs:
  using: composite
  steps:
    - name: Generate dev version
      id: version
      shell: bash
      run: |
        DEV_VERSION="$(date +'%Y%m%d')-${GITHUB_SHA::7}"
        echo "dev_version=$DEV_VERSION" >> $GITHUB_OUTPUT
        echo "Generated dev version: $DEV_VERSION"

    - name: Login to GHCR
      if: inputs.build_mode == 'dev' || inputs.build_mode == 'release'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr_token }}

    - name: Login to Docker Hub
      if: inputs.build_mode == 'dev' && inputs.dockerhub_username != ''
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Prepare image list
      id: images
      shell: bash
      run: |
        IMAGES="ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}"
        # In release mode, ONLY push to GHCR (Docker Hub comes later in publish-tags)
        if [ "${{ inputs.build_mode }}" != "release" ] && [ -n "${{ inputs.dockerhub_username }}" ]; then
          IMAGES="${IMAGES}"$'\n'"${{ inputs.dockerhub_username }}/${{ inputs.service_name }}"
        fi
        echo "images<<EOF" >> $GITHUB_OUTPUT
        echo "$IMAGES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.images.outputs.images }}
        tags: |
          ${{ inputs.docker_tag != '' && format('type=raw,value={0}', inputs.docker_tag) || format('type=raw,value=edge
          type=raw,value=dev
          type=raw,value={0}', steps.version.outputs.dev_version) }}
        labels: |
          org.opencontainers.image.title=${{ inputs.service_name }}
          org.opencontainers.image.description=YARMCP - Yet Another Repo MCP
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          ${{ inputs.full_version != '' && format('org.opencontainers.image.version={0}', inputs.full_version) || '' }}
          com.github.workflow=${{ github.workflow }}
          com.github.run-id=${{ github.run_id }}
          com.github.run-number=${{ github.run_number }}
          com.github.sha=${{ github.sha }}
          com.github.ref=${{ github.ref }}
          com.github.actor=${{ github.actor }}
          com.github.build-mode=${{ inputs.build_mode }}

    - uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context_path }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.build_mode == 'dev' || inputs.build_mode == 'release' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build_args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set up Python for tests
      if: |
        inputs.run_tests == 'true' ||
        (inputs.run_tests == 'auto' && (inputs.build_mode == 'test' || inputs.build_mode == 'release'))
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install test dependencies
      if: |
        inputs.run_tests == 'true' ||
        (inputs.run_tests == 'auto' && (inputs.build_mode == 'test' || inputs.build_mode == 'release'))
      shell: bash
      run: |
        if [ -f requirements-test.txt ]; then
          pip install -r requirements-test.txt
        elif [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        pip install pytest pytest-cov

    - name: Run Python tests
      if: |
        inputs.run_tests == 'true' ||
        (inputs.run_tests == 'auto' && (inputs.build_mode == 'test' || inputs.build_mode == 'release'))
      shell: bash
      run: |
        if [ -d "${{ inputs.context_path }}/tests" ]; then
          pytest ${{ inputs.context_path }}/tests -v --cov=${{ inputs.context_path }}
        elif [ -d "tests" ]; then
          pytest tests -v
        else
          echo "No tests found, skipping..."
        fi
