name: Docker Build and Push
description: Builds and pushes Docker image to GHCR and optionally Docker Hub with versioning

inputs:
  service_name:
    description: 'Service name for image tagging (e.g., yarmcp-mcp)'
    required: true
  context_path:
    description: 'Build context path (e.g., ./mcp-server)'
    required: true
  dockerfile:
    description: 'Path to Dockerfile (optional, defaults to Dockerfile in context)'
    required: false
  ghcr_token:
    description: 'GHCR authentication token (usually GITHUB_TOKEN)'
    required: true
  dockerhub_username:
    description: 'Docker Hub username (optional, for pushing to Docker Hub)'
    required: false
  dockerhub_token:
    description: 'Docker Hub token (optional, for pushing to Docker Hub)'
    required: false
  build_args:
    description: 'Build arguments (optional)'
    required: false
  is_release:
    description: 'Whether this is a release build (uses latest tag) or dev build (uses edge tag)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Generate version
      id: version
      shell: bash
      run: |
        DEV_VERSION="$(date +'%Y%m%d')-${GITHUB_SHA::7}"
        echo "dev_version=$DEV_VERSION" >> $GITHUB_OUTPUT
        echo "Generated dev version: $DEV_VERSION"

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.ghcr_token }}

    - name: Login to Docker Hub
      if: inputs.dockerhub_username != ''
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Prepare image list
      id: images
      shell: bash
      run: |
        IMAGES="ghcr.io/${{ github.repository_owner }}/${{ inputs.service_name }}"
        if [ -n "${{ inputs.dockerhub_username }}" ]; then
          IMAGES="${IMAGES}"$'\n'"${{ inputs.dockerhub_username }}/${{ inputs.service_name }}"
        fi
        echo "images<<EOF" >> $GITHUB_OUTPUT
        echo "$IMAGES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.images.outputs.images }}
        tags: |
          type=raw,value=${{ inputs.is_release == 'true' && 'latest' || 'edge' }}
          type=raw,value=dev
          type=raw,value=${{ steps.version.outputs.dev_version }}
        labels: |
          org.opencontainers.image.title=${{ inputs.service_name }}
          org.opencontainers.image.description=YARMCP - Yet Another Repo MCP
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

    - uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context_path }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build_args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
